"""Main page layout and user-intent signals, independent of business state."""

from PySide6.QtCore import Qt, Signal
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import (
    QComboBox,
    QFrame,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListView,
    QScrollArea,
    QVBoxLayout,
    QWidget,
)

from ..platform.paths import platform_name
from .widgets import make_button, resource_path


class MainView(QWidget):
    profile_changed = Signal(int)
    new_profile_requested = Signal()
    rename_profile_requested = Signal()
    delete_profile_requested = Signal()
    sources_requested = Signal()
    settings_requested = Signal()
    refresh_requested = Signal()
    filters_changed = Signal()

    def __init__(self, parent=None):
        super().__init__(parent)
        row = QHBoxLayout(self)
        row.setContentsMargins(0, 0, 0, 0)
        row.setSpacing(0)

        sidebar = QFrame()
        sidebar.setObjectName("sidebar")
        sidebar.setFixedWidth(238)
        side = QVBoxLayout(sidebar)
        side.setContentsMargins(21, 24, 21, 22)
        side.setSpacing(12)
        brand_row = QHBoxLayout()
        logo = QLabel()
        icon = resource_path("assets/icon.svg")
        if icon.exists():
            logo.setPixmap(QIcon(str(icon)).pixmap(47, 47))
        brand_row.addWidget(logo)
        brand = QLabel("期刊雷达")
        brand.setObjectName("brand")
        brand_row.addWidget(brand)
        brand_row.addStretch()
        side.addLayout(brand_row)
        caption = QLabel("跨学科文献订阅 · " + platform_name())
        caption.setObjectName("sidebarCaption")
        side.addWidget(caption)
        side.addSpacing(30)
        label = QLabel("当前学科")
        label.setObjectName("sidebarCaption")
        side.addWidget(label)
        self.profile_box = QComboBox()
        self.profile_box.setView(QListView())
        self.profile_box.currentIndexChanged.connect(self.profile_changed.emit)
        side.addWidget(self.profile_box)
        self.new_profile_button = make_button("＋ 新建学科", "sidebarAction")
        self.new_profile_button.clicked.connect(self.new_profile_requested.emit)
        side.addWidget(self.new_profile_button)
        profile_actions = QHBoxLayout()
        self.rename_button = make_button("重命名", "sidebarAction")
        self.delete_profile_button = make_button("删除", "sidebarAction")
        self.rename_button.clicked.connect(self.rename_profile_requested.emit)
        self.delete_profile_button.clicked.connect(self.delete_profile_requested.emit)
        profile_actions.addWidget(self.rename_button)
        profile_actions.addWidget(self.delete_profile_button)
        side.addLayout(profile_actions)
        side.addSpacing(22)
        self.nav_papers = make_button("近期论文", "navActive")
        self.nav_sources = make_button("管理期刊来源", "nav")
        self.nav_settings = make_button("翻译与网络设置", "nav")
        self.nav_papers.clicked.connect(lambda: self.paper_scroll.ensureVisible(0, 0))
        self.nav_sources.clicked.connect(self.sources_requested.emit)
        self.nav_settings.clicked.connect(self.settings_requested.emit)
        side.addWidget(self.nav_papers)
        side.addWidget(self.nav_sources)
        side.addWidget(self.nav_settings)
        side.addStretch()
        tip = QLabel("可添加 RSS 或 ISSN\n译文仅在点击时生成")
        tip.setObjectName("sidebarCaption")
        tip.setWordWrap(True)
        side.addWidget(tip)
        row.addWidget(sidebar)

        content = QWidget()
        main = QVBoxLayout(content)
        main.setContentsMargins(32, 29, 32, 24)
        main.setSpacing(17)
        header = QHBoxLayout()
        titles = QVBoxLayout()
        titles.setSpacing(5)
        self.page_title = QLabel()
        self.page_title.setObjectName("pageTitle")
        self.page_subtitle = QLabel("把不同学科的期刊放在各自工作区，集中查看新论文。")
        self.page_subtitle.setObjectName("pageSubtitle")
        titles.addWidget(self.page_title)
        titles.addWidget(self.page_subtitle)
        header.addLayout(titles, 1)
        self.refresh_button = make_button("↻  刷新来源", "primary")
        self.refresh_button.clicked.connect(self.refresh_requested.emit)
        header.addWidget(self.refresh_button)
        main.addLayout(header)

        stats = QHBoxLayout()
        stats.setSpacing(13)
        self.source_stat = self.make_stat("期刊来源")
        self.paper_stat = self.make_stat("缓存论文")
        self.updated_stat = self.make_stat("最近刷新")
        for frame, _value in (self.source_stat, self.paper_stat, self.updated_stat):
            stats.addWidget(frame, 1)
        main.addLayout(stats)

        controls = QHBoxLayout()
        self.search = QLineEdit()
        self.search.setPlaceholderText("搜索标题或期刊名称…")
        self.search.setClearButtonEnabled(True)
        self.search.textChanged.connect(lambda _text: self.filters_changed.emit())
        controls.addWidget(self.search, 1)
        self.source_filter = QComboBox()
        self.source_filter.setMinimumWidth(160)
        self.source_filter.currentIndexChanged.connect(lambda _index: self.filters_changed.emit())
        controls.addWidget(self.source_filter)
        self.date_filter = QComboBox()
        self.date_filter.addItem("全部时间", 0)
        self.date_filter.addItem("近 7 天（精确日期）", 7)
        self.date_filter.addItem("近 30 天（精确日期）", 30)
        self.date_filter.setToolTip("来源只有期刊月份、没有具体日期的论文不会被纳入 7/30 天筛选。")
        self.date_filter.currentIndexChanged.connect(lambda _index: self.filters_changed.emit())
        controls.addWidget(self.date_filter)
        main.addLayout(controls)

        section_row = QHBoxLayout()
        section_title = QLabel("近期论文")
        section_title.setObjectName("sectionTitle")
        section_row.addWidget(section_title)
        section_row.addStretch()
        self.result_count = QLabel()
        self.result_count.setObjectName("pageSubtitle")
        section_row.addWidget(self.result_count)
        main.addLayout(section_row)

        self.paper_scroll = QScrollArea()
        self.paper_scroll.setWidgetResizable(True)
        self.paper_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.paper_holder = QWidget()
        self.paper_layout = QVBoxLayout(self.paper_holder)
        self.paper_layout.setContentsMargins(0, 0, 8, 0)
        self.paper_layout.setSpacing(11)
        self.paper_layout.setAlignment(Qt.AlignmentFlag.AlignTop)
        self.paper_scroll.setWidget(self.paper_holder)
        main.addWidget(self.paper_scroll, 1)
        self.status_label = QLabel("就绪")
        self.status_label.setObjectName("notice")
        main.addWidget(self.status_label)
        row.addWidget(content, 1)

    def make_stat(self, label: str) -> tuple[QFrame, QLabel]:
        frame = QFrame()
        frame.setObjectName("statCard")
        column = QVBoxLayout(frame)
        column.setContentsMargins(19, 15, 19, 15)
        column.setSpacing(4)
        value = QLabel("—")
        value.setObjectName("statValue")
        caption = QLabel(label)
        caption.setObjectName("statLabel")
        column.addWidget(value)
        column.addWidget(caption)
        return frame, value
